CREATE TABLE tokens (
  id INTEGER NOT NULL PRIMARY KEY,
  client INTEGER NOT NULL REFERENCES credentials(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  token INTEGER NOT NULL REFERENCES credentials(id) ON DELETE CASCADE ON UPDATE CASCADE,
  user INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  UNIQUE (client, token, user)
);
